print("hallo cuyy")
print("selamat pagi")
print("ihhiihihih")
print("jangan lupa bersenang-senang")
print("lepas")
print("janji gak janji")
print("sokin lu orangnya asik bang")
print("hati-hati di jalan")
print("infon")
print("full turu")